
[package]
org = "ballerinax"
name = "cds_server"
version = "1.0.0"
distribution = "2201.9.2"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "CRD", "Da Vinci", "CDS", "Coverage Requirements Discovery"]
template = true
